### ISSUE TITLE
1.16.5 - TODO List

### ISSUE THREAD

**Issue by DerToaster98** [TeamChocoQuest/ChocolateQuestRepoured#379]
Entities:
- [ ] Migrate AI to SmartBrainLib
- [ ] Fix how EntityData gets accessed on clients. Those are or will be threadlocked, so on client write their value to a normal field and access that in the getter
- [ ] Move all creations of animationbuilders to constants
- [ ] Fix walking animation (too slow)
- [ ] Add arm movement to walking animation
- [ ] Fix navigation
- [ ] Fix that entities continue to walk in a direction when they actually should stop
- [ ] Fix swing animation playing too late
- [ ] Fix summoning circles spinning randomly
- [ ] Fix facing target taking really long
- [ ] Migrate shelob to glib

General:
- [ ] Implement basic magic system to replace spell-AI
- [x] Fix and update protected regions
- [ ] Sync up with 1.12.2 patches
- [ ] Decide what will happen to rCastles
- [ ] Fix and update translations
- [ ] Fix loottables
- [x] ~~Backport AzureLib to 1.16.5 and use it to replace geckolib (AzureLib is basically adjusted geckolib4, which in many cases is nicer to use than geckolib3)~~
- [ ] Migrate to geckolib 4 (WIP)
- [x] Fix mixins (WIP)
- [x] Fix gradle not working
- [x] Fix installation of default files
- [ ] Some entity values don't seem to save (faction, custom texture data, etc)
- [ ] Banners are buggy (wrong colors, missing patterns)
- [ ] Pirate parrot always throws potions and hurts itself
- [ ] Migrate things to glib:
    - [ ] shelob
    - [ ] crown
    - [ ] heavy armor
    - [ ] bull armor
    - [ ] tortoise armor
    - [ ] spider armor
    - [ ] backpack
    - [ ] cloud boots (maybe add some small wings that flap in the air?)
    - [ ] dragon helmet
- [ ] Add entity-properties datapacking
    - [ ] datapackable file per entity
    - [ ] defines base size
    - [ ] defines base health
    - [ ] defines base faction
    - [ ] defines texture count
    - [ ] defines any entity attribute optionally

Visuals:
- [ ] Update item and block textures to match MC's new artstyle
- [ ] Finally update the remaining rendering classes
- [x] Finally implement new model of ForceFieldNexus
- [ ] Create Glowlayer that does not rely on the special json => AzureLib or geckolib feature
- [ ] Boss block has crown texture on top 
- [ ] Inventory model of nexus
- [ ] Dyable armor: item models don't get colored
- [ ] Custom loottable chests => a lot of missing textures
- [ ] Weird shading on 3d items
- [ ] Pirate parrot "moves down" the longer it lives
- [ ] Pirate parrot wings perform a circling motion
- [ ] Exterminator doesn't stop his attack animation

WorldGen:
- [x] Fix lakes generating in structures
- [ ] Fix trees spawning in structures
- [x] Fix underground lake thing
- [ ] Fix banners
- [ ] Fix loottables not being assigned
- [x] Fix existing weathering processors
- [ ] Clean up structure classes
- [ ] Add actual usage of the processors
- [ ] (MAYBE) add support for jigsaw pieces
- [x] Fix new world's being unable to generate
- [ ] Fix heads losing their "texture"

Structure-gen issues:
- [x] Lakes inside of structures
- [ ] Lootchests don't have any loottable assigned
- [ ] Spawners are empty (vanilla spawners too)
- [ ] Banners appear blank
- [ ] Signs don't have text
- [ ] Trees spawn inside structures
- [ ] Waterlogging
- [ ] Waterboarders at edges
- [ ] A lot of warnings and errors in the logs when a structure spawns

**Comment by quentin452** [comment]
@DerToaster98 Azurelib is already backported to 1.16.5

**Comment by DerToaster98** [comment]
Ye i know, i helped backporting it.

Don't ping me please

**Comment by DerToaster98** [comment]
Issue locked to collaborators cause it is meant as a TODO list and nothing else
